---
- hosts: app
  roles:
    - common
    #- java
  tasks:

    - name: Install unzip
      apt: pkg=unzip state=installed
      environment: "{{ proxy_env }}"
      sudo: yes

    - name: Create app directory
      file: path={{ rights_app_dest }} state=directory
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Clear rights-app Download
      file: path="{{ rights_app_dest }}/rights-app-dist.zip" state=absent
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Download rights-app release
      get_url: url="{{ rights_app_repo_url }}/releases/download/{{ rights_app_release }}/rights-app-dist.zip" dest="{{ rights_app_dest }}/rights-app-dist.zip" validate_certs=no
      sudo: yes
      sudo_user: "{{ deployment_user }}"
      environment: "{{ proxy_env }}"

    - stat: path="{{ rights_app_dest }}/rights-app-dist.zip"
      register: download
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - fail: msg="Download of {{ rights_app_release }} failed"
      when: not download.stat.exists
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Extract rights-app
      shell: cd "{{ rights_app_dest }}" && unzip -o rights-app-dist.zip
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Copy rights-app startup script
      template: src=templates/startup.sh dest="{{ rights_app_dest }}/rights-app-dist/" mode=755
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Copy rights-app shutdown script
      template: src=templates/shutdown.sh dest="{{ rights_app_dest }}/rights-app-dist/" mode=755
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: Copy rights-app init script
      template: src=templates/rights-app dest=/etc/init.d/ mode=755
      sudo: yes

    - name: Enable rights-app init
      shell: update-rc.d rights-app defaults
      sudo: yes

    - include: roles/app/tasks/restart.yml
