---
- hosts: site
  vars_files:
    - vars.yml
  tasks:
    - name: Install nodejs
      apt: state=present name=nodejs
      sudo: yes
    
    - name: Install curl
      apt: state=present name=curl
      sudo: yes

    - name: Check for RVM
      stat: path={{ home }}/.rvm/scripts/rvm
      register: rvm

    - name: Install RVM key
      shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      when: rvm.stat.exists == false

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      when: rvm.stat.exists == false

    - name: Install RVM requirements
      shell: . "{{ home }}/.rvm/scripts/rvm" && rvm requirements
      when: rvm.stat.exists == false
      args:
        executable: /bin/bash

    - name: Install Ruby 2.1.2
      shell: . "{{ home }}/.rvm/scripts/rvm" && rvm install 2.1.2
      when: rvm.stat.exists == false
      args:
        executable: /bin/bash
    
    - name: Install Jekyll
      shell: . "{{ home }}/.rvm/scripts/rvm" && gem install jekyll
      when: rvm.stat.exists == false
      args:
        executable: /bin/bash

    - name: Checkout project from Git
      git: repo={{ site_repo_url }} dest={{ site_dest }} remote={{ site_repo_remote }} version={{ site_repo_version }} update=yes

    - name: Create Jekyll config
      template: src=templates/_config_jekyll.yml dest={{ site_dest }}/_ansible_config.yml

    - name: Stop Jekyll
      shell: bash -c "ps aux | grep '{{ home }}/.rvm/gems/ruby-2.1.2/bin/[jekyll]'" | awk '{print $2}' | xargs kill
      ignore_errors: true
      args:
        executable: /bin/bash

    - name: Start Jekyll
      shell: cd "{{ site_dest }}" && . "{{ home }}/.rvm/scripts/rvm" && screen -S jekyll -d -m jekyll serve --host=0.0.0.0 --port={{ site_port }} --config _config.yml,_ansible_config.yml
      args:
        executable: /bin/bash

    - name: Wait for jekyll
      wait_for: port={{ site_port }} delay=5
