---
- hosts: app
  vars_files:
    - vars.yml
  tasks:
    - name: Install the Git package
      apt: pkg=git state=installed
      sudo: yes

    - name: Install Oracle Java Repo Installer Repository
      apt_repository: repo=ppa:webupd8team/java update-cache=yes 
      sudo: yes
      register: javarepo

    - name: Wizardry to bypass the Oracle License File prompt
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
      sudo: yes
      when: javarepo.changed
  
    - name: Install Oracle Java 8
      apt: pkg=oracle-java8-installer state=installed
      sudo: yes

    - name: Add sbt repository key
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x642AC823 state=present
      sudo: yes

    - name: Install sbt repository
      apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present update-cache=yes
      sudo: yes

    - name: Install sbt
      apt: pkg=sbt state=installed
      sudo: yes

    - name: Checkout project from Git
      git: repo={{ rights_app_repo_url }} dest={{ rights_app_dest }} remote={{ rights_app_repo_remote }} version={{ rights_app_repo_version }} update=yes
      register: gitclone

    - name: Build rights-app
      shell: cd "{{ rights_app_dest }}" && sbt clean stage
      when: gitclone.changed

    - stat: path={{ rights_app_dest }}/target/universal/stage/RUNNING_PID
      register: pid

    - name: Stop rights-app
      shell: cat "{{ rights_app_dest }}/target/universal/stage/RUNNING_PID" | xargs kill
      when: pid.stat.exists

    - name: Start rights-app
      shell: cd "{{ rights_app_dest }}" && screen -S rights-app -d -m target/universal/stage/bin/rights-app -Dhttp.port={{ rights_app_port }}

    - name: Wait for rights-app
      wait_for: port={{ rights_app_port }} delay=20

