---
- hosts: app
  vars_files:
    - vars.yml
  tasks:
    - name: Install Oracle Java Repo Installer Repository
      apt_repository: repo=ppa:webupd8team/java update-cache=yes 
      sudo: yes
      register: javarepo

    - name: Wizardry to bypass the Oracle License File prompt
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
      sudo: yes
      when: javarepo.changed
  
    - name: Install Oracle Java 8
      apt: pkg=oracle-java8-installer state=installed
      sudo: yes

    - name: Install unzip
      apt: pkg=unzip state=installed
      sudo: yes

    - name: Find latest release
      shell: >
        curl -s -L -H 'Accept: application/json' {{ rights_app_repo_url }}/releases/latest | grep -Po '"tag_name":"\K[^"]*'
      when: rights_app_release == "latest"
      register: latest
      ignore_errors: True

    - name: Download latest rights-app release
      get_url: url={{ rights_app_repo_url }}/releases/download/{{ latest.stdout }}/rights-app-dist.zip dest={{ rights_app_dest }}
      when: latest.rc == 0

    - name: Download rights-app release
      get_url: url={{ rights_app_repo_url }}/releases/download/{{ rights_app_release }}/rights-app-dist.zip dest={{ rights_app_dest }}
      when: latest is undefined

    - name: Extract rights-app
      shell: cd "{{ rights_app_dest }}" && unzip -o rights-app-dist.zip

    - stat: path={{ rights_app_dest }}/rights-app-dist/RUNNING_PID
      register: pid

    - name: Stop rights-app
      shell: cat "{{ rights_app_dest }}/rights-app-dist/RUNNING_PID" | xargs kill
      when: pid.stat.exists

    - name: Start rights-app
      shell: cd "{{ rights_app_dest }}/rights-app-dist/" && screen -S rights-app -d -m bin/rights-app -Dhttp.port={{ rights_app_port }}

    - name: Wait for rights-app
      wait_for: port={{ rights_app_port }} delay=5

