---
- hosts: proxy
  roles:
    - apache
  tasks:

    - name: Install Apache proxy module
      apt: pkg=libapache2-mod-proxy-html state=installed update_cache=true
      environment: "{{ proxy_env }}"
      sudo: yes

    - name: Enable apache proxy modules
      shell: a2enmod {{item}}
      with_items:
        - proxy
        - proxy_ajp
        - proxy_http
        - rewrite
        - deflate
        - headers
        - proxy_balancer
        - proxy_connect
        - proxy_html
        - xml2enc
      notify:
        - reload apache2
      sudo: yes

    - name: create virtual host file
      template: src=templates/proxy-vhost.conf dest=/etc/apache2/sites-available/{{ proxy_vhost }}.conf
      notify:
        - reload apache2
      sudo: yes

    - name: a2ensite {{ proxy_vhost }}
      command: a2ensite {{ proxy_vhost }}
      notify:
        - reload apache2
      sudo: yes

    - name: a2dissite 000-default
      command: a2dissite 000-default
      notify:
        - reload apache2
      sudo: yes

    - name: reload apache2
      service: name=apache2 state=reloaded
      notify:
        - reload apache2
      sudo: yes
