---
- hosts: site
  roles:
    - common
    - apache
  tasks:
    - name: Configure Apache port
      lineinfile: dest=/etc/apache2/ports.conf line="Listen {{ rights_site_port }}"
      notify:
        - reload apache2
      sudo: yes

    - name: Checkout site from GitHub
      git: repo="{{ rights_site_repo_url }}" dest="{{ rights_site_dest }}" version="{{ rights_site_build_branch }}" update=yes
      environment: "{{ proxy_env }}"
      sudo: yes
      sudo_user: "{{ deployment_user }}"

    - name: create virtual host file
      template: src=templates/site-vhost.conf dest=/etc/apache2/sites-available/{{ rights_site_vhost }}.conf
      notify:
        - reload apache2
      sudo: yes

    - name: a2ensite {{ rights_site_vhost }}
      command: a2ensite {{ rights_site_vhost }}
      notify:
        - reload apache2
      sudo: yes

    - name: a2dissite 000-default
      command: a2dissite 000-default
      notify:
        - reload apache2
      sudo: yes

    - name: Wait for rights-site
      wait_for: port={{ rights_site_port }} delay=5
