#! /bin/sh
### BEGIN INIT INFO
# Provides:          rights-app
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rights-app initscript
# Description:       This script starts and stops the rights-app server
### END INIT INFO

APP_DIR={{ rights_app_dest }}/rights-app-dist/

case "$1" in
 start)
   su {{ deployment_user }} -c $APP_DIR/shutdown.sh
   sleep 20
   su {{ deployment_user }} -c $APP_DIR/startup.sh
   ;;
 stop)
   su {{ deployment_user }} -c $APP_DIR/shutdown.sh
   sleep 10
   ;;
 restart)
   su {{ deployment_user }} -c $APP_DIR/shutdown.sh
   sleep 20
   su {{ deployment_user }} -c $APP_DIR/startup.sh
   ;;
 *)
   echo "Usage: rights-app {start|stop|restart}" >&2
   exit 3
   ;;
esac
